# Generated by Django 6.1.1 on 2026-09-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
