# Generated by Django 6.1.1 on 2026-10-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('student', '0002_alter_student_must_change_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='uses_transport',
        ),
        migrations.AddField(
            model_name='student',
            name='transport_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='fees.transportlocation'),
        ),
    ]
